"use client";

import { useState } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/Button";

interface DownloadButtonProps {
  files: Record<string, { code: string }>;
  projectName?: string;
}

export function DownloadButton({ files, projectName = "mrui-generated-site" }: DownloadButtonProps) {
  const [isGeneratingZip, setIsGeneratingZip] = useState(false);

  const handleDownload = async () => {
    setIsGeneratingZip(true);
    try {
      const zip = new JSZip();
      const appCode = files["/App.js"]?.code ?? "export default function App() { return <main />; }";
      const stylesCode = files["/styles.css"]?.code ?? "";

      zip.file("package.json", JSON.stringify({
        name: projectName,
        private: true,
        version: "1.0.0",
        type: "module",
        scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
        dependencies: { "@vitejs/plugin-react": "latest", vite: "latest", react: "latest", "react-dom": "latest" },
      }, null, 2));

      zip.file("index.html", `<!doctype html>
<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><script src="https://cdn.tailwindcss.com"></script><title>${projectName}</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`);
      zip.file("src/App.jsx", appCode);
      zip.file("src/styles.css", stylesCode);
      zip.file("src/main.jsx", `import React from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./styles.css";\n\ncreateRoot(document.getElementById("root")).render(<React.StrictMode><App /></React.StrictMode>);\n`);
      zip.file("README.md", `# ${projectName}\n\nGenerated by MrUI.\n\n## Run locally\n\n\`npm install\`\n\`npm run dev\`\n`);

      saveAs(await zip.generateAsync({ type: "blob" }), `${projectName}.zip`);
    } catch (error) {
      console.error("ZIP generation error:", error);
      window.alert("Could not prepare the ZIP file. Please try again.");
    } finally {
      setIsGeneratingZip(false);
    }
  };

  return (
    <Button
      onClick={handleDownload}
      disabled={isGeneratingZip}
      variant="default"
      className="gap-2 shadow-[0_0_20px_rgba(168,85,247,0.3)]"
    >
      <Download className="w-4 h-4" />
      {isGeneratingZip ? "Preparing ZIP…" : "Download ZIP"}
    </Button>
  );
}
